import os
import sys


from setuptools import setup

setup(
    name="apiteam22dsa",
    packages=["apiteam22dsa"],
    version="1.0",
    description="Libreria que contiene la API del equipo 22 de la Asignatura Despliegue de soluciones analíticas para facilitar su instalación",
    author="JECaballeroR",
    author_email="je.caballero@uniandes.edu.co",
    install_requires=[
        "fastapi==0.104.1",
        "joblib==1.3.2",
        "mock==5.1.0",
        "pandas",
        "pydantic==2.5.2",
        "Requests==2.31.0",
        "scikit_learn==1.3.2",
        "matplotlib==3.8.1",
        "numpy==1.26.1",
        "pca==2.0.5",
        "pingouin==0.5.3",
        "plotly==5.18.0",
        "ppscore==1.3.0",
        "seaborn==0.13.0",
        "streamlit",
        "uvicorn==0.24.0.post1",
        "python-decouple==3.8",
        "openpyxl",
    ],
    setup_requires=[
        "fastapi==0.104.1",
        "joblib==1.3.2",
        "mock==5.1.0",
        "pandas",
        "pydantic==2.5.2",
        "Requests==2.31.0",
        "scikit_learn==1.3.2",
        "matplotlib==3.8.1",
        "numpy==1.26.1",
        "pca==2.0.5",
        "pingouin==0.5.3",
        "plotly==5.18.0",
        "ppscore==1.3.0",
        "seaborn==0.13.0",
        "streamlit",
        "uvicorn==0.24.0.post1",
        "python-decouple==3.8",
        "openpyxl",
    ],
    tests_require=[
        "scikit_learn==1.3.2",
        "pandas",
        "pytest>=4.4.1",
        "pytest-cov>=2.0",
        "mypy>=0.910",
        "flake8>=3.9",
        "tox>=3.24.4",
        "pytest-runner==5.3.1",
        "bandit==1.7.1",
        "pylint==2.12.2",
        "black==22.3.0",
    ],
    test_suite="tests",
    license="MIT",
    include_package_data=True,
    python_requires=">=3.9",
)
